--Q1.What is the total revenue generated by male vs female customers?
select gender,SUM(purchase_amount) as revenue from customer group by gender

--Q2.Which customers used discount still spent more than the average purchace amount?
select customer_id,purchase_amount from customer 
where discount_applied='Yes' and purchase_amount >=(select AVG(purchase_amount) from customer)

--Q3.Which are the top 5 productws with the highest average review rate?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating" from customer
group by item_purchased order by AVG(review_rating) desc limit 5;

--Q4.Compare the average Purchase Amounts between Standrad and Express Shipping.
select shipping_type, ROUND(AVG(purchase_amount),2) from customer where shipping_type in ('Standard','Express')
group by shipping_type

--Q5.Do subscribed customers spend more ? Cimpare average spend and total revenue between subscribers and non-subscribers
select subscription_status,COUNT (customer_id) as total_customers,ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue from customer group by subscription_status order by total_revenue,avg_spend desc; 

--Q6.Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END )/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7.Segmemt customers into New ,Returning and Loyal based on their total number of previous purchases ,and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
CASE
	WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as Customer_segment
from customer
)

select customer_segment,count (*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8.What are the top 3 most purchased products withn each category?
